In [8]:
import numpy as np

def self_attention(X):
    batch_size, seq_len, d_model = X.shape
    d_k = d_model

    W_q = np.random.randn(d_model, d_k)
    W_k = np.random.randn(d_model, d_k)
    W_v = np.random.randn(d_model, d_k)

    Q = X @ W_q  
    K = X @ W_k
    V = X @ W_v

    scores = Q @ K.transpose(0, 2, 1) / np.sqrt(d_k)  

    attention_weights = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)

    output = attention_weights @ V

    return output, attention_weights

In [9]:
np.random.seed(42)
X = np.random.rand(1, 3, 2) ##

output, weights = self_attention(X)

print("Output:\n", output)
print("\nAttention Weights:\n", weights)

Output:
 [[[-1.06520883 -0.06236256]
  [-1.02802454 -0.0576073 ]
  [-1.24274075 -0.05872247]]]

Attention Weights:
 [[[0.20879264 0.27140899 0.51979837]
  [0.20875851 0.24564775 0.54559374]
  [0.30361171 0.31681591 0.37957238]]]


In [19]:
X1 = np.random.rand(1)
X2 = np.random.rand(1,2)##2D
X3 = np.random.rand(1,2,1) #3D with 1 column and 2 rows
X4 = np.random.rand(1,2,2) #3D with 2 columns and 2 rows
batch_size,seq_len,d_model = X4.shape

print(X1)
print(f'\n{X2}')
print(f'\n{X3}')
print(f'\n{X4}')

[0.12203823]

[[0.49517691 0.03438852]]

[[[0.9093204 ]
  [0.25877998]]]

[[[0.66252228 0.31171108]
  [0.52006802 0.54671028]]]


In [20]:
batch_size, seq_len, d_model

(1, 2, 2)

In [22]:
d_model
d_k = d_model
d_k

2

In [26]:
W_Q=np.random.rand(d_model, d_k)
W_V=np.random.rand(d_model, d_k)
W_K=np.random.rand(d_model, d_k)

Q = X4@W_Q
V = X4@W_V
K = X4@W_K

In [27]:
W_Q, Q

(array([[0.07404465, 0.35846573],
        [0.11586906, 0.86310343]]),
 array([[[0.0851739 , 0.50653043],
         [0.10185506, 0.65829408]]]))

In [30]:
scores = Q @ K.transpose(0,2,1)/np.sqrt(d_k)
scores

array([[[0.29713107, 0.34081461],
        [0.38356733, 0.43969223]]])

In [11]:
class Student:
    def __init__(self):
        # Public
        self.name = "Mike"          
        # Protected
        self._roll_no = 101         
        # Private
        self.__marks = 95            

obj = Student()
print(obj.name)      
print(obj._roll_no)
print(obj._Student__marks)

Mike
101
95


In [32]:
!pip install torch

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached markupsafe-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.3/127.3 MB 4.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.6/206.6 kB 6.8 MB/s eta 0:00:00
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 12.9 MB/s eta 0:00:0000:01
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 1.0 MB/s eta 0:00:00 0:00:01
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp312-cp312-macosx_11_0_arm64.whl (12 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

[notice] A new release of pip is av

In [44]:
import torch

##array
x = torch.tensor([1, 2, 3])

In [45]:
type(x)

torch.Tensor

## How you create the tensor with pytorch?

In [ ]:
import torch
##create tensor with list of 1D array
a = torch.tensor([1, 2, 3])

##create 2D tensor of zeros(elements) of 3-rows and 4-columns
b = torch.zeros(3, 4)

##create 2D tensor of ones(elements) of 2-rows and 3-columns
c = torch.ones(2, 3)

##create 2D tensor of random(elements) of 2-rows and 3-columns between 0-1
d = torch.rand(2, 3)

##create 2D tensor of normally distributed random sampled(elements) of 2-rows and 3-columns 
e = torch.randn(2, 3)

##create 1D array of 0-10 with step of 2
f = torch.arange(0, 10, 2)

##create array for line including end value
g = torch.linspace(0, 1, steps=5)

In [53]:
b = torch.linspace(0, 10, 5)
b

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])